baseurl = "https://shickmo.github.io/hugo-site/"
themesDir = "themes"
publishDir = "docs"
title = "shickmo.io"
author = "Shickmo"
paginate = 3
theme = "bluestnight"
PygmentsCodeFences = true
PygmentsStyle = "monokai"
enableRobotsTXT = true # Suggested, enable robots.txt file

[outputs]
    home = ["HTML", "CSS", "JSON", "RSS"]

[Params]
    tagline = "Feel the open source breeze in the air"
    description = "" # Description of your site
    authorbox = true
    author = "Shickmo"
    post_navigation = false

[Params.widgets]
    search = true
    recent_articles = true
    categories = true
    tags = true
    tags_counter = true
    patreon = "shickmo"

[Params.color]
    page_background = "#000000"
    main_background = "#050505"
    alt_background = "#252525"
    main_text = "#e2e2e2"
    alt_text = "#e2e2e2"
    accent = "#2c8cef"
    accent_text = "#e2e2e2"

[Params.social]
   #twitter = "shickmo7"
   #youtube = "UCaRXarF0L3H6gIPVZszr87w"

[menu]
  [[menu.main]]
    name = "Posts"
    weight = 1
    identifier = "docs"
    url = "#"
 #[[menu.main]]
    #name = "Social"
    #weight = 1
   [[menu.main]]
     name = "Email"
     weight = 1
     parent = "social"
     url = "mailto:shickmoshow@gmail.com"
   [[menu.main]]
     name = "Mastodon"
     weight = 1
     parent = "social"
     url = "https://mastodon.technology/@shickmo"
   [[menu.main]]
     name = "Twitter"
     weight = 1
     parent = "social"
     url = "https://twitter.com/shickmo7"
   [[menu.main]]
     name = "YouTube"
     weight = 1
     parent = "social"
     url = "https://www.youtube.com/channel/UCaRXarF0L3H6gIPVZszr87w" 
  #[[menu.main]]
   #name = "Email"
   #weight = 2
   #url = "mailto:shickmoshow@gmail.com"   
    #[[menu.main]]
      #name = "Pages"
      #weight = 1
      #parent = "docs"
      #identifier = "docs-pages"
      #url = "#"
    #[[menu.main]]
      #name = "Shortcodes"
      #weight = 1
      #parent = "docs"
      #identifier = "docs-shortcodes"
      #url = "#"
    #[[menu.main]]
      #name = "Sidebar"
      #weight = 1
      #parent = "docs"
      #identifier = "docs-sidebar"
      #url = "#"
    #[[menu.main]]
      #name = "Site"
      #weight = 1
      #parent = "docs"
      #identifier = "docs-site"
      #url = "#"
  #[[menu.main]]
    #name = "Tutorials"
    #weight = 10
    #identifier = "tutorials"
    #url = "#"
