baseurl = "/"
themesDir = "themes"
publishDir = "docs"
title = "shickmo.io"
copyright = "Copyright (c) 2017, all rights reserved."
paginate = 3
theme = "hugo-dusk"
languageCode = "en-US"

[author]
  name = "shickmo"

SectionPagesMenu = "main"


[[menu.main]]
  name = "Posts"
  weight = -120
  identifier = "post"
  url = "/post/"

[[menu.main]]
  name = "Tags"
  weight = -110
  identifier = "tags"
  url = "/tags/"

[[menu.main]]
  name = "Categories"
  weight = -100
  identifier = "categories"
  url = "/categories/"

[params]
  youtube = "UCaRXarF0L3H6gIPVZszr87w"
  twitter = "shickmo7"
  email = "shickmoshow@gmail.com"
  mastodon = "shickmo"
  patreon = "shickmo"
