baseurl = "https://shickmo.github.io/hugo-site/"
themesDir = "themes"
publishDir = "docs"
title = "shickmo.io"
copyright = "Copyright (c) 2017, all rights reserved."
canonifyurls = true
paginate = 3
theme = "hugo-dusk"
languageCode = "en-US"

[author]
    name = "shickmo"

[params]
    youtube = "UCaRXarF0L3H6gIPVZszr87w"
    twitter = "shickmo7"
    email = "shickmoshow@gmail.com"
    mastodon = "shickmo"
    patreon = "shickmo"

[menu]
  [[menu.main]]
    name = "Posts"
    weight = -120
    identifier = "post"
    url = "/post/"
